version: '3'

services:
  db:
    image: 'bitnami/postgresql:15.2.0'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ignite-daily-diet-api
    ports:
      - 5432:5432
